project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"

website:
  title: "Introduction to the Command Line"
  navbar:
    search: true
    left:
      - href: https://digbmc.github.io/dssf-syll/
        text: DSSF Syllabus
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Introduction
      - href: sections/what-is-the-command-line.md
        text: What is the command line?
      - href: sections/text-editors.md
        text: Working with text
      - href: sections/why-is-the-command-line-useful.md
        text: Why is the command line useful?
      - href: sections/getting-to-the-command-line.md
        text: Getting to the command line    
      - href: sections/navigation.md
        text: Navigation
      - href: sections/creating-files-and-folders.md
        text: Creating files and folders
      - href: sections/creating-a-cheat-sheet.md
        text: Creating a cheat sheet
      - href: sections/pipes.md
        text: Pipes
      - href: sections/data.md
        text: Exploring text data
      - href: sections/grep.md
        text: Searching text data
      - href: sections/summary.md
        text: Summary of what we've covered
      - section: Resources
        contents:
          - sections/commands.md
          - sections/challenges.md
          - sections/glossary.md
  page-footer: Bryn Mawr College Digital Scholarship, 2024
  page-navigation: true

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



